apiVersion: v1
kind: ConfigMap
metadata:
  name: commafeed-configmap
data:
  CF_APP_PUBLICURL: "https://commafeed-stg.sandeshsolabannavar.com"
  CF_DATABASE_DRIVERCLASS: "org.postgresql.Driver"
  CF_DATABASE_URL: "jdbc:postgresql://commafeed-db-staging-cnpg-v1-rw.commafeed:5432/app"
