apiVersion: v1
kind: Service
metadata:
  name: prowlarr-vpn
  namespace: arr-stack
spec:
  selector:
    app: prowlarr-vpn
  ports:
    - port: 80
      targetPort: 9696
      name: http
  type: ClusterIP
