---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: arr-stack
spec:
  selector:
    app: prowlarr
  ports:
    - name: prowlarr
      targetPort: 9696
      port: 9696
      protocol: TCP
---

