apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  labels:
    app: prowlarr
spec:
  selector:
    app: prowlarr
  ports:
    - name: http
      port: 80
      targetPort: 9697
  type: ClusterIP
