apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infotropyiq
resources:
  - namespace.yaml
  - token-refresher.yaml
  - deployment-au.yaml
  - deployment-germany.yaml
  - deployment-dashboard.yaml
  - redis.yaml
  - deployment-email-workers.yaml
  - cronjob-email-pipeline.yaml
