apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: redis-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: redis-operator
      version: "0.22.2"
      sourceRef:
        kind: HelmRepository
        name: ot-container-kit
        namespace: redis-operator
      interval: 12h

  values:
    replicas: 3

  install:
    createNamespace: true
    remediation:
      retries: 3
