apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ot-container-kit
  namespace: redis-operator
spec:
  interval: 24h
  url: https://ot-container-kit.github.io/helm-charts
