apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.9.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    createNamespace: true
  values:
    defaultSettings:
      defaultDataPath: "/var/lib/longhorn"
      defaultReplicaCount: 3
      defaultDataLocality: disabled
      replicaSoftAntiAffinity: true
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      backupTarget: ""
      backupTargetCredentialSecret: ""
      allowRecurringJobWhileVolumeDetached: true
      createDefaultDiskLabeledNodes: true
      defaultLonghornStaticStorageClass: longhorn
      storageOverProvisioningPercentage: 200
      storageMinimalAvailablePercentage: 10
      upgradeChecker: false
      # Enable RWX volumes (requires NFS client support in nodes)
      nfsBackupVolumes: true
      replicaAutoBalance: best_effort
      orphanAutoDeletion: true

    preUpgradeChecker:
      jobEnabled: false

    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
      defaultFsType: ext4
      reclaimPolicy: Retain

    ingress:
      enabled: false

    service:
      ui:
        # -- Service type for Longhorn UI. (Options: "ClusterIP", "NodePort", "LoadBalancer", "Rancher-Proxy")
        type: ClusterIP
