apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: infotropyiq
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 3
  template:
    metadata:
      labels:
        app: cloudflared
        policy-type: "app"
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10

          ports:
            - containerPort: 2000
              name: http-metrics

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi

          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: creds
              mountPath: /etc/cloudflared/creds/
              readOnly: true

      restartPolicy: Always

      volumes:
        - name: config
          configMap:
            name: cloudflared
            items:
              - key: config.yaml
                path: config.yaml
        - name: creds
          secret:
            secretName: cloudflare-tunnel
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: infotropyiq
data:
  config.yaml: |
    # Name of the tunnel you want to run
    tunnel: infotropyiq
    credentials-file: /etc/cloudflared/creds/credentials.json

    metrics: 0.0.0.0:2000

    no-autoupdate: true

    ingress:
    - hostname: stg-app.infotropyiq.com
      service: http://infotropyiq-web:80

    - hostname: hello.infotropyiq.com
      service: hello_world

    # This rule matches any traffic which didn't match a previous rule, and responds with HTTP 404.
    - service: http_status:404
