apiVersion: batch/v1
kind: CronJob
metadata:
  name: free-credits-sync
  namespace: infotropyiq
spec:
  schedule: "0 */6 * * *" # Every 6 hours
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sync
              image: 192.168.1.11:5000/infotropyiq-server:latest
              command: ["bun", "run", "free-credits"]
              envFrom:
                - secretRef:
                    name: infotropyiq-env
          restartPolicy: OnFailure
