---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisReplication
metadata:
  name: redis-replication
  namespace: infotropyiq
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/redis:latest
    imagePullPolicy: IfNotPresent
    redisSecret:
      name: redis-secret
      key: redis-password
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: local-path
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
  redisExporter:
    enabled: false
    image: quay.io/opstree/redis-exporter:latest
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
