apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infotropyiq-env
  namespace: infotropyiq
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: BETTER_AUTH_SECRET
      remoteRef:
        key: better-auth-secret
    - secretKey: REDIS_URL
      remoteRef:
        key: redis-url
    - secretKey: POLAR_ACCESS_TOKEN
      remoteRef:
        key: polar-access-token
    - secretKey: DATABASE_URL
      remoteRef:
        key: database-url
    - secretKey: OPENROUTER_API_KEY
      remoteRef:
        key: openrouter-api-key
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: openai-api-key
    - secretKey: MEILISEARCH_API_KEY
      remoteRef:
        key: meili-master-key
    - secretKey: GNEWS_KEY
      remoteRef:
        key: gnews-key
    - secretKey: RESEND_API_KEY
      remoteRef:
        key: resend-api-key
    - secretKey: POLAR_WEBHOOK_SECRET
      remoteRef:
        key: polar-webhook-secret
    - secretKey: CONTACT_REVEAL_CREDIT_COST
      remoteRef:
        key: contact-reveal-credit-cost
    - secretKey: POLAR_REVEAL_CONTACT_METER_ID
      remoteRef:
        key: polar-reveal-contact-meter-id
    - secretKey: POLAR_SERVER
      remoteRef:
        key: polar-server-sandbox
    - secretKey: POLAR_AI_ADVANCED_SEARCH_METER_ID
      remoteRef:
        key: polar-ai-advanced-search-meter-id
    - secretKey: POLAR_PROFILE_VIEWS_METER_ID
      remoteRef:
        key: polar-profile-views-meter-id
    - secretKey: POLAR_STARTER_PRODUCT_ID
      remoteRef:
        key: polar-starter-product-id
    - secretKey: POLAR_PROFESSIONAL_PRODUCT_ID
      remoteRef:
        key: polar-professional-product-id
    - secretKey: POLAR_SUCCESS_URL
      remoteRef:
        key: polar-success-url-stg
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-secret
  namespace: infotropyiq
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: redis-password
      remoteRef:
        key: redis-password
