apiVersion: v1
kind: Service
metadata:
  name: health-app-server
  namespace: health-app
spec:
  selector:
    app: health-app-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
