apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shoetracker
resources:
  - ../../base/shoetracker
  - cloudflare.yaml
  - secrets.yaml
  - database.yaml
  - scheduled-backup.yaml
