apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: shoetracker-db-backup
  namespace: shoetracker
spec:
  schedule: "0 0 2 * * *"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: shoetracker-db
