apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: meilisearch
  namespace: meilisearch
spec:
  interval: 1h
  url: https://meilisearch.github.io/meilisearch-kubernetes
