apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: apps-pool
  namespace: kube-system
spec:
  blocks:
    - start: "172.19.0.196"
      stop: "172.19.0.210"

  serviceSelector:
    matchLabels:
      cilium-lb-pool: apps-pool
