apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: ingress-pool
  namespace: kube-system
spec:
  blocks:
    - start: "172.19.0.192"
      stop: "172.19.0.195"

  serviceSelector:
    matchLabels:
      cilium.io/ingress: "true"
