apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  releaseName: metallb
  interval: 10m
  install:
    createNamespace: true
  targetNamespace: metallb-system
  chart:
    spec:
      chart: metallb
      version: 0.15.2 # Use latest stable version available
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: metallb-values
      valuesKey: values.yaml
