apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: interview-pilot-db-backup
  namespace: interview-pilot
spec:
  schedule: "0 0 3 * * *"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: interview-pilot-db
