apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: interview-pilot-db-secret
  namespace: interview-pilot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: password
      remoteRef:
        key: interview-pilot-db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: interview-pilot-cnpg-s3-creds
  namespace: interview-pilot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: ahey-chat-aws-access-key-id
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: ahey-chat-aws-secret-access-key
    - secretKey: AWS_DEFAULT_REGION
      remoteRef:
        key: ahey-chat-aws-region
