apiVersion: v1
kind: Service
metadata:
  name: carousel-file-server
  namespace: carousel-agent
  labels:
    app: carousel-approval-bot
spec:
  type: LoadBalancer
  selector:
    app: carousel-approval-bot
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
