apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plane-rabbitmq-auth
  namespace: plane
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: RABBITMQ_DEFAULT_USER
      remoteRef:
        key: plane-rabbitmq-default-user
    - secretKey: RABBITMQ_DEFAULT_PASS
      remoteRef:
        key: plane-rabbitmq-default-pass
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plane-postgres-auth
  namespace: plane
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: plane-postgres-password
    - secretKey: POSTGRES_DB
      remoteRef:
        key: plane-postgres-db
    - secretKey: POSTGRES_USER
      remoteRef:
        key: plane-postgres-user
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plane-app-env
  namespace: plane
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: plane-app-secret-key
    - secretKey: REDIS_URL
      remoteRef:
        key: plane-redis-url
    - secretKey: DATABASE_URL
      remoteRef:
        key: plane-database-url
    - secretKey: AMQP_URL
      remoteRef:
        key: plane-amqp-url
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plane-live-env
  namespace: plane
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: REDIS_URL
      remoteRef:
        key: plane-redis-url
    - secretKey: LIVE_SERVER_SECRET_KEY
      remoteRef:
        key: plane-live-server-secret-key
---

