apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare-secrets.yaml
  - ../../base/headlamp
  - cloudflare.yaml
patches:
  - path: headlamp-values.yaml
    target:
      kind: HelmRelease
