apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik
  - cert-manager
  - cloudnativepg
  - external-secrets
  - redis-operator
  # - local-path
  - meilisearch
  # - flux-capacitor
  - rancher
