apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: arr-stack
spec:
  chart:
    spec:
      chart: radarr
      sourceRef:
        kind: HelmRepository
        name: radarr
  interval: 50m0s
  values:
    env:
      TZ: "Asia/Kolkata"
