---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: infiniq-web
  namespace: infiniq
  labels:
    app: infiniq-web
spec:
  replicas: 3
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: infiniq-web
  template:
    metadata:
      labels:
        app: infiniq-web
    spec:
      containers:
        - name: infiniq-web
          image: 192.168.1.11:5000/infiniq-web@sha256:016b840f7bda78501b5c44a4f0922079e5f84b8ac41e1bd98f79e18f62cf1619
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "256Mi"
          ports:
            - containerPort: 80
