---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: infiniq-web
  namespace: infiniq
  labels:
    app: infiniq-web
spec:
  replicas: 3
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: infiniq-web
  template:
    metadata:
      labels:
        app: infiniq-web
    spec:
      containers:
        - name: infiniq-web
          image: 192.168.1.11:5000/infiniq-web@sha256:78fe1a999ded119de6a26e6700ce7979b3bdb6b3e70fbf3f9c862e11882b8dc2
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "256Mi"
          ports:
            - containerPort: 80
