---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: infiniq-web
  namespace: infiniq
  labels:
    app: infiniq-web
spec:
  replicas: 3
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: infiniq-web
  template:
    metadata:
      labels:
        app: infiniq-web
    spec:
      containers:
        - name: infiniq-web
          image: 192.168.1.11:5000/infiniq-web@sha256:f13ce3b5ceba57a74c677fdcc6944798e31525a7f57e769408fb2c52233854b3
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "256Mi"
          ports:
            - containerPort: 80
