apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: arr-stack
  labels:
    app: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: gluetun
          image: qmcgaw/gluetun
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - "NET_ADMIN"
          env:
            - name: TZ
              value: "Asia/Kolkata"
            - name: VPN_SERVICE_PROVIDER
              value: privado
            - name: VPN_TYPE
              value: openvpn
            - name: SERVER_COUNTRIES
              value: United States
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: gluetun-env
                  key: OPENVPN_USER
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gluetun-env
                  key: OPENVPN_PASSWORD
          ports:
            - containerPort: 8888 # optional: Gluetun's HTTP control server
            - containerPort: 9696 # if routing via Gluetun and exposing
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "Asia/Kolkata"
          ports:
            - containerPort: 9696
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config-pvc
          # 🧠 Use gluetun's network namespace by not setting your own
          # Optional: add health/liveness probes if needed
      restartPolicy: Always
