apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr-vpn
  namespace: arr-stack
  labels:
    app: prowlarr-vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr-vpn
  template:
    metadata:
      labels:
        app: prowlarr-vpn
    spec:
      containers:
        - name: prowlarr-vpn
          image: binhex/arch-prowlarr
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: VPN_ENABLED
              value: "yes"
            - name: VPN_PROV
              valueFrom:
                secretKeyRef:
                  name: gluetun-env
                  key: VPN_SERVICE_PROVIDER
            - name: VPN_USER
              valueFrom:
                secretKeyRef:
                  name: gluetun-env
                  key: OPENVPN_USER
            - name: VPN_PASS
              valueFrom:
                secretKeyRef:
                  name: gluetun-env
                  key: OPENVPN_PASSWORD
            - name: TZ
              value: "Asia/Kolkata"
            - name: UMASK
              value: "002"
            - name: DEBUG
              value: "false"
            - name: DOT
              value: "off"
            - name: DNS
              value: "1.1.1.1,8.8.8.8"
            - name: LAN_NETWORK
              value: "10.42.0.0/16,192.168.1.0/24"
            - name: VPN_DISABLE_IPV6
              value: "yes"
          ports:
            - containerPort: 9696
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config-pvc
