apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gluetun-env
  namespace: arr-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: VPN_SERVICE_PROVIDER
      remoteRef:
        key: vpn-service-provider
    - secretKey: OPENVPN_USER
      remoteRef:
        key: openvpn-user
    - secretKey: OPENVPN_PASSWORD
      remoteRef:
        key: openvpn-password
    - secretKey: SERVER_COUNTRIES
      remoteRef:
        key: server-countries
