apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  releaseName: traefik
  interval: 10m
  install:
    createNamespace: true
  targetNamespace: traefik
  chart:
    spec:
      chart: traefik
      version: 36.3.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  valuesFiles:
    - values.yaml
