apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
resources:
  - helm-repository.yaml
  - traefik-values-configmap.yaml
  - helm-release.yaml
