apiVersion: apps/v1
kind: Deployment
metadata:
  name: commafeed
  namespace: commafeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commafeed

  template:
    metadata:
      labels:
        app: commafeed
        try: "0"
        policy-type: "app"

    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000

      containers:
        - name: commafeed
          image: athou/commafeed:4.5.0

          securityContext:
            allowPrivilegeEscalation: false

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          env:
            - name: CF_DATABASE_USER
              valueFrom:
              secretKeyRef:
                name: commafeed-db-staging-cnpg-v1-app
                key: user
            - name: CF_DATABASE_PASSWORD
              valueFrom:
              secretKeyRef:
                name: commafeed-db-staging-cnpg-v1-app
                key: password
            - name: CF_APP_PUBLICURL
              value: "https://commafeed-stg.sandeshsolabannavar.com"
            - name: CF_DATABASE_DRIVERCLASS
              value: "org.postgresql.Driver"
            - name: CF_DATABASE_URL
              secretKeyRef:
                name: commafeed-db-staging-cnpg-v1-app
                key: jdbc-uri
          ports:
            - containerPort: 8082
              protocol: TCP

      restartPolicy: Always
